# 어플리케이션의 호스트 부분
app:
  host: http://anabada-shop.tk

#업로드 포트
server:
  port: 80

spring:
  #JPA 설정
  jpa:
    hibernate:
      ddl-auto: update

  #프로필 관련
  profiles:
    include: credentials

#로깅 관련
logging:
  level:
    root: error
